---
- hosts: win-host
  gather_facts: false
  tasks:

  - name: Ensure user bob is present
    win_user:
      name: bob2
      password: B0bP4ssw0rd
      state: present
      groups:
        - Users
