---
- hosts: 10.0.2.15
  connection: local
  gather_facts: false
  tasks:

  - name: Ensure user bob is present
    win_user:
      name: bob1
      password: B0bP4ssw0rd
      state: present
      groups:
        - Users
