---
- hosts: win-host
  gather_facts: false
  connection: local
  tasks:

  - name: Ensure user bob is present
    win_user:
      name: bob
      password: B0bP4ssw0rd
      state: present
      groups:
        - Users
