---
- hosts: host-win
  gather_facts: false
  vars_prompt:

    - name: change_ref
      prompt: What is the change ref?
      private: no

  tasks:
   - name: Write an entry to a Windows event log
     win_eventlog_entry:
       log: Application
       source: Ansible
       event_id: 6666
       message: Firmware updated via "{{ change_ref }}"
