---
- hosts: host-win
  gather_facts: false

  vars_prompt:

  - name: change_ref
    prompt: What is the change ref?
    private: no

  - name: implementor
    prompt: Who is implenting this change?
    private: no

  tasks:
  - name: get the affected windows host's uptime
    win_shell: "[convert]::ToInt32(($(Get-Date) - $(Get-WmiObject Win32_OperatingSystem).ConvertToDateTime($(Get-WmiObject Win32_OperatingSystem).LastBootUpTime)).TotalMInutes);"
    register: uptime_raw
    changed_when: false
    ignore_errors: true

  - name: Save Uptime related variables
    set_fact:
    #  uptime_mins: "{{ uptime_raw.stdout_lines[0] }}"
      uptime_hours: "{{ uptime_raw.stdout_lines[0] | int / 60 }}"

  - debug:
      msg: "uptime is {{uptime_hours}} hours"

  - name: Write an entry to a Windows event log
    win_eventlog_entry:
      log: Application
      source: Ansible
      event_id: 65535
      message: "Firmware updated via {{ change_ref }} \n\nImplemented by {{ implementor }} \n\nServer uptime {{uptime_hours}}"
