---
- hosts: host-win
  gather_facts: false

  tasks:
  - name: Obtain information about a file
    win_stat:
      path: C:\services.csv
    register: file_info

  - name: Obtain information about a folder
    win_stat:
      path: C:\Windows
    register: folder_info

#  - debug: msg="{{ folder_info }} & {{ folder }}"
  - name: information
    debug:
      msg: "Folders\n\n{{ folder_info }} \n\n  & \n\n File \n\n {{ file_info }}"
