---
- hosts: host-win
  gather_facts: false

  tasks:
  - name: Get info for all installed services
    ansible.windows.win_service_info:
    register: service_info

  - name: edit only display_name
    set_fact:
      dis_name: "{{ service_info.display_name.stdout_lines[0] }}"

#  - name: print to screen
#    debug:
#      msg: "{{display_name.service_info}}"
