---
- hosts: host-win
  gather_facts: false

  tasks:
  - name: Find all serv
    ansible.windows.win_service_info:
    register: service_info

  - name: print to screen
    debug:
      msg: "{{service_info.display_name[x]}}"
#      msg: "{{service_info}}"
