---
- hosts: host-win
  gather_facts: false

  tasks:

  - name: Get info for all installed services
    ansible.windows.win_service_info:
      name: state
    register: services_info

  - name: print to screen
    debug:
      msg: " installed windows services \n\n {{services_info}}"
