---
- hosts: host-win
  gather_facts: false
  vars:
    services_info

  tasks:

  - name: Get info for all installed services
    ansible.windows.win_service_info:
    register: services_info

  - debug:
      msg: services_info
