---
- hosts: host-win
  gather_facts: false
#  become_method: runas

  tasks:
  - name: get the affected windows host's uptime
    win_shell: Get-Service | Export-Csv -path "C:\services.csv"
#    become: yes
#    become_user: Administrator
    register: service
    changed_when: false
    ignore_errors: true

#  - name: print to screen
#    debug:
#      msg: "{{ service }}"

#  - name: Write Windows event log
#    win_eventlog_entry:
#      log: Application
#      source: Ansible
#      event_id: 65535
#      message: "{{ service }}"

#  - name: Find all serv
#    ansible.windows.win_service_info:
#    register: service_info

#  - name: print to screen
#    debug:
#      msg: "{{service_info.display_name[9]}}"
#      msg: "{{service_info}}"
