---
- hosts: host-win
  gather_facts: false

  tasks:
  - name: Get info for all installed services
    ansible.windows.win_service:
      name: WinRM
    register: service_info

  - name: print to screen
    debug:
      msg: "{{service_info}}"
