---
- hosts: host-win
  gather_facts: false

  tasks:

  - name: Get info for all installed services
    ansible.windows.win_service_info:
    register: service_info

  - name: services
    set_fact:
      services: "{{ service_info | int }}"

  - debug:
      msg: services
