---
- hosts: host-win
  gather_facts: false

  tasks:
  - name: Get info for all installed services
    ansible.windows.win_service_info: display_name
    register: services_info

  - name: print to screen
    debug:
      msg: "{{services_info}}"
