---
- name: Play to demonstrate vars prompt feature
  hosts: host-win
  gather_facts: no

  vars_prompt:
     - name: username
       prompt: "Enter username:"
       private: no

     - name: user_password
       prompt: "Enter Password:"
       private: yes
       encrypt: sha256_crypt
       confirm: yes

  tasks:
     - name: Create user {{ username }}
       user:
         name: "{{ username }}"
         password: "{{ user_password }}"
